all:
  tenants:
      dev:
          tenant_name:    b2c-integration-suite-dev
          oAuthUrl:       https://b2c-integration-suite-dev.authentication.us10.hana.ondemand.com/oauth/token?grant_type=client_credentials
          baseURL:        https://b2c-integration-suite-dev.it-cpitrial06.cfapps.us10-001.hana.ondemand.com/api/v1/IntegrationPackages
          PackageURL:     https://b2c-integration-suite-dev.it-cpitrial06.cfapps.us10-001.hana.ondemand.com/api/v1/IntegrationPackages('{{ item }}')/IntegrationDesigntimeArtifacts
          ArtifactsURL:   https://b2c-integration-suite-dev.it-cpitrial06.cfapps.us10-001.hana.ondemand.com/api/v1/IntegrationDesigntimeArtifacts(Id='{{id}}',Version='{{version}}')/$value
          client_id:      sb-1c644ea7-1da5-472c-b2ab-a146c61a6276!b269340|it!b55215
          client_secret:  425384e7-6f6b-4f22-8fbe-caa0659fbd45$2nPpnmrUSVjX5XRlXovyOqpw982P55UupHP0tqpWHJc=
      stage:
          tenant_name:    fair-consulting-group-sap-integration-sandbox-he862lcw
          oAuthUrl:       https://fair-consulting-group-sap-integration-sandbox-he862lcw.authentication.ap10.hana.ondemand.com/oauth/token?grant_type=client_credentials
          baseURL:        https://fair-consulting-group-sap-integration-sandbox-he862lcw.it-cpi002.cfapps.ap10.hana.ondemand.com/api/v1/IntegrationPackages
          PackageURL:     https://fair-consulting-group-sap-integration-sandbox-he862lcw.it-cpi002.cfapps.ap10.hana.ondemand.com/api/v1/IntegrationPackages('{{ item }}')/IntegrationDesigntimeArtifacts
          ArtifactsURL:   https://fair-consulting-group-sap-integration-sandbox-he862lcw.it-cpi002.cfapps.ap10.hana.ondemand.com/api/v1/IntegrationDesigntimeArtifacts(Id='{{id}}',Version='{{version}}')/$value
          client_id:      sb-f677d17d-4767-410f-9bd3-4dd6a08eb538!b43602|it!b80
          client_secret:  2c101bd5-7e5f-4502-8faf-f1c678d444b1$JqegEZTP5lMaXZtRzc3wtjjws0YRf0Fll5YNe7_fVeo=
