name: Configure iFlow

on:
  workflow_dispatch:
    inputs:
      iflow_name:
        description: 'ID of the iFlow to configure'
        required: true
      environment:
        description: 'Environment for the configuration'
        required: true
        type: choice
        options:
        - dev
        - prod

jobs:
  configure_iflow:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download single iFlow
        run: |
          python download_single_iflow.py --iflow "${{ github.event.inputs.iflow_name }}" --output_dir "./Get_All_Packages"
        env:
          OAUTH_URL: ${{ secrets.OAUTH_URL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          BASE_URL: ${{ secrets.BASE_URL }}
          PACKAGE_URL: ${{ secrets.PACKAGE_URL }}
          ARTIFACTS_URL: ${{ secrets.ARTIFACTS_URL }}

      - name: Create environment-specific config
        run: |
          IFLOW_PATH=$(find ./Get_All_Packages -type d -name "${{ github.event.inputs.iflow_name }}")
          python create_iflow_config.py --iflow "${{ github.event.inputs.iflow_name }}" --env "${{ github.event.inputs.environment }}" --output_dir "$IFLOW_PATH"
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat(iflow): Add ${{ github.event.inputs.iflow_name }} config for ${{ github.event.inputs.environment }}"
          title: "feat(iflow): Configure ${{ github.event.inputs.iflow_name }} for ${{ github.event.inputs.environment }}"
          body: |
            This PR adds the environment-specific configuration and the downloaded artifact for the `${{ github.event.inputs.iflow_name }}` iFlow in the `${{ github.event.inputs.environment }}` environment.
          branch: "feature/iflow-${{ github.event.inputs.iflow_name }}-${{ github.event.inputs.environment }}"
          base: "main"
