name: iFlow Mass Downloader

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run against'
        required: true
        type: choice
        options:
        - dev
        - stage
        default: 'dev'
      approver:
        description: 'GitHub username of the person to assign as a reviewer'
        required: true

jobs:
  download:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: iflowmassdownloader

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r iflowmassdownloader/requirements.txt
    
    - name: Run iFlow downloader
      run: python iflowmassdownloader/downloadiFlows.py
      env:
        OAUTH_URL: ${{ secrets.OAUTH_URL }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        BASE_URL: ${{ secrets.BASE_URL }}
        PACKAGE_URL: ${{ secrets.PACKAGE_URL }}
        ARTIFACTS_URL: ${{ secrets.ARTIFACTS_URL }}
        OUTPUT_DIR: ./downloaded_iflows

    - name: Checkout target repository
      uses: actions/checkout@v3
      with:
        repository: msrivastava16/cement-integration
        token: ${{ secrets.TARGET_REPO_PAT }}
        path: target_repo

    - name: Create and switch to new branch
      id: branch
      run: |
        cd target_repo
        BRANCH_NAME="iflow-updates-$(date +'%Y-%m-%d-%H-%M-%S')"
        git checkout -b "$BRANCH_NAME"
        echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
        echo "Created and switched to branch: $BRANCH_NAME"
      shell: bash

    - name: Copy downloaded iFlows to target repository
      run: |
        mkdir -p target_repo/Get_All_Packages
        cp -r downloaded_iflows/* target_repo/Get_All_Packages/

    - name: Commit and push to target repository
      run: |
        cd target_repo
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Add downloaded iFlows from workflow run on $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push --set-upstream origin ${{ steps.branch.outputs.branch_name }}
      shell: bash