name: iFlow Mass Downloader

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run against'
        required: true
        type: choice
        options:
        - dev
        - stage
        default: 'dev'

jobs:
  download:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Run iFlow downloader
      run: python downloadiFlows.py
      env:
        OAUTH_URL: ${{ secrets.OAUTH_URL }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        BASE_URL: ${{ secrets.BASE_URL }}
        PACKAGE_URL: ${{ secrets.PACKAGE_URL }}
        ARTIFACTS_URL: ${{ secrets.ARTIFACTS_URL }}
        OUTPUT_DIR: ./Get_All_Packages

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "feat(iflows): Update iFlows from workflow run"
        title: "feat(iflows): Update iFlows"
        body: "This PR contains the latest iFlows downloaded from the `${{ github.event.inputs.environment }}` environment."
        branch: "iflow-updates-${{ github.run_id }}"
        base: "main"
