name: Upload iFlows from Content Repository

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'The repository to restore iFlows from'
        required: true
        default: 'msrivastava16/cement-integration'
      branch:
        description: 'The branch of the content repository to use to restore iflows'
        required: true
        default: 'main'
      environment:
        description: 'Environment to run against'
        required: true
        type: choice
        options:
        - dev
        - stage
        default: 'dev'

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Content Repository
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.inputs.repository }}
        ref: ${{ github.event.inputs.branch }}
        path: content_repo

    - name: Checkout Script Repository
      uses: actions/checkout@v3
      with:
        path: script_repo

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r script_repo/requirements.txt

    - name: Verify Secrets are Loaded
      run: |
        if [ -z "${{ secrets.OAUTH_URL }}" ]; then echo "OAUTH_URL secret is NOT set"; exit 1; else echo "OAUTH_URL secret is set."; fi
        if [ -z "${{ secrets.CLIENT_ID }}" ]; then echo "CLIENT_ID secret is NOT set"; exit 1; else echo "CLIENT_ID secret is set."; fi
        if [ -z "${{ secrets.CLIENT_SECRET }}" ]; then echo "CLIENT_SECRET secret is NOT set"; exit 1; else echo "CLIENT_SECRET secret is set."; fi
        if [ -z "${{ secrets.BASE_URL }}" ]; then echo "BASE_URL secret is NOT set"; exit 1; else echo "BASE_URL secret is set."; fi
      shell: bash

    - name: Run uploader script
      run: |
        python script_repo/createPackageAndFlows.py --source-dir content_repo/Get_All_Packages
      env:
        OAUTH_URL: ${{ secrets.OAUTH_URL }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        BASE_URL: ${{ secrets.BASE_URL }}
